### ISSUE TITLE
Mappings/filter titles

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/find-sdg-research#32]
1. Made a new mapping for language on the carrie-more-mappings branch, not pull requested yet cause unsure about point 2.
2. I also started mapping "Scientific (NVI)" and "Fulltext found", but I remembered these are boolean filters, and they just use the filter title if I remember right - so I guess a normal mapping will not work?
3. Feedback from group meeting today 1 - filter titles can't be translated, but could we change them to include both languages? e.g. "Fulltext / Fulltekst"?
4. Feedback from group meeting today 2 - could "NVI level" be mapped as "Level 1" (en) and "Nivå 1" (no)? (instead of just "1")

**Comment by tarjelavik** [comment]
1. Unsure on point 1
2. Correct, i think
3. They probably can
4. That was the way i originally did it ;-). Create PR and i can fix the facet filter name
