### ISSUE TITLE
Found broken link. Please fix!

### ISSUE THREAD

**Issue by Caroline-A** [SDGforskning/find-sdg-research#88]
SDG4 link broken from homepage (english version, SDG4 icon link), found now when sending the site to someone. 

`/ok?filters%5B0%5D%5Bvalues%5D%5B0%5D=true&size=n_20_n&filters%5B0%5D%5Btype%5D=all&filters%5B1%5D%5Btype%5D=any&filters%5B1%5D%5Bvalues%5D%5B0%5D=SDG4%20Quality%20education&filters%5B1%5D%5Bfield%5D=SDG_topic_en.keyword&filters%5B0%5D%5Bfield%5D=fulltext_found.keyword`

(@tarjelavik rememeber that you created this issue template, don't get mad about the tone in the title ;))

**Comment by tarjelavik** [comment]
Fixed :-). Got a scare; but that is ok.
